# Usa una imagen base oficial de Python
FROM python:3.8

# Configura el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia los archivos requirements.txt y randomForest.py al contenedor
COPY requirements.txt ./
COPY randomForest.py ./

# Instala las bibliotecas necesarias en el contenedor
RUN pip install --no-cache-dir -r requirements.txt

# Comando para ejecutar el script cuando se inicie el contenedor
CMD ["python", "./randomForest.py"]
